spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://:3306/score_assistant?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
web:
  resources:
    static-locations: classpath:static/,classpath:/templates/

get-score-cmd: "python3 /root/project/get_grades.py"
user-data-path: "/root/project/user_data/"
springfox:
  documentation:
    enabled: true
server:
  port: 8081
  servlet:
    context-path: /wz
